behaviors:
  ReachTargetObstacle:
    trainer_type: ppo
    max_steps: 2000000
    time_horizon: 128
    summary_freq: 10000
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 10
    checkpoint_interval: 50000
    behavioral_cloning: null
