behaviors:
  ReachTargetObstacle:
    trainer_type: ppo
    max_steps: 2000000
    time_horizon: 256
    summary_freq: 10000
    hyperparameters:
      batch_size: 4096
      buffer_size: 65536
      learning_rate: 3.0e-4
      beta: 8.0e-3
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.01
        gamma: 0.99
        learning_rate: 3.0e-4
    keep_checkpoints: 10
    checkpoint_interval: 50000
    behavioral_cloning: null

# Trainer-wide settings
env_settings:
  num_envs: 8
torch_settings:
  device: cuda
