behaviors:
  ReachTargetCurriculum:
    trainer_type: ppo
    max_steps: 10000000
    time_horizon: 512
    summary_freq: 15000
    hyperparameters:
      batch_size: 4096
      buffer_size: 65536
      learning_rate: 3.0e-4
      beta: 5.0e-3
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.01
        gamma: 0.99
        learning_rate: 3.0e-4
    keep_checkpoints: 10
    checkpoint_interval: 50000
    behavioral_cloning: null

env_settings:
  num_envs: 64

torch_settings:
  device: cuda

environment_parameters:
  shhhunt_curriculum_stage:
    curriculum:
      - name: ground-only
        completion_criteria:
          measure: reward
          behavior: ReachTargetCurriculum
          signal_smoothing: true
          min_lesson_length: 50000
          threshold: 0.7
        value:
          sampler_type: constant
          sampler_parameters:
            value: 0
      - name: obstacles-enabled
        completion_criteria:
          measure: reward
          behavior: ReachTargetCurriculum
          signal_smoothing: true
          min_lesson_length: 60000
          threshold: 0.85
        value:
          sampler_type: constant
          sampler_parameters:
            value: 1
      - name: structures-enabled
        completion_criteria:
          measure: reward
          behavior: ReachTargetCurriculum
          signal_smoothing: true
          min_lesson_length: 70000
          threshold: 0.95
        value:
          sampler_type: constant
          sampler_parameters:
            value: 2
      - name: elevated-targets
        value:
          sampler_type: constant
          sampler_parameters:
            value: 3
